trigger:
  branches:
    include:
    - main
    - develop
  paths:
    exclude:
    - .gitignore

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build
    displayName: Build
    pool:
      vmImage: 'ubuntu-24.04'
    workspace:
      clean: all
    steps:
    
    - checkout: self
      submodules: true
      fetchTags: true
      fetchDepth: 0
      persistCredentials: true
      
    - task: gitversion/setup@0
      inputs:
        versionSpec: 5.x
      
    - task: gitversion/execute@0
      inputs:
        versionSpec: 5.x
    
    - pwsh: Write-Host "##vso[build.updatebuildnumber]$(GitVersion.FullSemVer)"
      displayName: Set Build Number

    - publish: $(Build.SourcesDirectory)
      displayName: Publish
      condition: always()
      artifact: artifacts

- stage: deploy
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy
  variables:
  - group: awg-appdev-platform-labs
  jobs:
  - template: deploy.yml
    parameters:
      environment: awg-appdev-sandbox
      subscription: awg-appdev-sandbox
